#!/bin/bash

source "${LIB_DIR}/common.sh"

usage() {
    cat << EOF
Usage: $CMD_NAME destroy [INTERFACE]

    destroy interface configuration

Options:
    -h, --help            show this help message

Examples:
    $CMD_NAME destroy eth0
EOF
    exit 1
}

# Parse options
while getopts "h-:" opt; do
    case $opt in
        -)
            case "${OPTARG}" in
                help) usage ;;
                *) log_error "Invalid option: --$OPTARG" ;;
            esac;;
        h) usage ;;
        \?) log_error "Invalid option: -$OPTARG" ;;
    esac
done

shift $((OPTIND-1))
iface="$1"

if [ -z "$iface" ]; then
    log_error "Interface name is required"
fi

if [ -f "${INTERFACES_D}/$iface" ]; then
    rm "${INTERFACES_D}/$iface"
    log_message "Configuration for interface $iface has been removed"
else
    log_error "Configuration for interface $iface not found"
fi
