#!/bin/bash

source "${LIB_DIR}/common.sh"

usage() {
    cat << EOF
Usage: $CMD_NAME dsr [OPTIONS]

    direct server return configuration generator

Options:
    -a, --auto            up interface after reboot
    -i, --iface TEXT      interface name
    -p, --ip IPv4         ip address
    -f, --file            generate configuration file in $INTERFACES_D
    -h, --help            show this help message

Examples:
    $CMD_NAME dsr -a -i dsr0 -p 192.168.0.1
    $CMD_NAME dsr -a -i dsr0 -p 192.168.0.1 -f
EOF
    exit 1
}

auto_iface_up=false
iface=""
address=""
generate_file=false

# Parse options
while getopts "ai:p:fh-:" opt; do
    case $opt in
        -)
            case "${OPTARG}" in
                auto) auto_iface_up=true ;;
                iface) iface="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 )) ;;
                ip) address="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 )) ;;
                file) generate_file=true ;;
                help) usage ;;
                *) log_error "Invalid option: --$OPTARG" ;;
            esac;;
        a) auto_iface_up=true ;;
        i) iface="$OPTARG" ;;
        p) address="$OPTARG" ;;
        f) generate_file=true ;;
        h) usage ;;
        \?) log_error "Invalid option: -$OPTARG" ;;
    esac
done

# Validate input
[ -z "$iface" ] && log_error "Interface name is required"
[ -z "$address" ] && log_error "IP address is required"

validate_interface "$iface"
validate_ip "$address"

# Generate configuration
config=""
$auto_iface_up && config+="auto $iface\n"
config+="iface $iface inet static
    pre-up ip link add $iface type dummy
    pre-down ip link del $iface type dummy
    address $address
    netmask 255.255.255.255
"

handle_file_generation "$config" "$iface" "$generate_file"
